PYTHON
¿QUE ES UN PROGRAMA??

ES EL CONJUNTO DE INSTRUCCIONES LOGICAS Y PASOS ORDENADOS QUE SE DISEÑAN PARA QUE UN SISTEMA,COMO UNA COMPUTADORA REALICE UNA TAREA ESPECIFICA

VARIABLES

VIMOS COMO FUNCIONA UN CONJUNTO DE CIRCUITOS CONFORMADOS POR UNA CANTIDAD DE PEQUEÑOS NUMEROS DE LOS CUALES AL HACER UNA CONEXION PUEDE QUE EMITA LA LUZ O NO, DADO ESE CASO,ESTAS VARIABLES SON LA ENTRADA A LA PROGRAMACION MEDIANTE INFORMACION QUE SE LE ASIGNA POR CODIGOS O ALGORITMOS

<NOMBRE_DE_LA_VARIABLE> = <valor>

PRINT("HOLA MUNDO")

PIENSO QUE LA MANERA EN LA QUE SE PUEDE UTILIZAR EL LENGUAJE DE PROGRAMACION, ES BASTANTE SOFISTICADA PARA APRENDER A CONECTARNOS CON LA MANERA EN LA QUE DEBE COMUNICAR CON LOS CODIGOS Y SABER DIFERENCIAR EL ENTORNO DE LO QUE CONLLEVA EL APRENDER A PROGRAMAR, DE ESTA MANERA LA PLATAFORMA DE GITHUB LA HABIA VISUALIZADO TIEMPO ATRAS PERO NO LA HABIA UTILIZADO MUCHO,DE HECHO TENIA CUENTA CREADA CON EL CORREO PERSONAL PERO YA LO TENGO CON LA DE LA IU, ESPERO SEGUIR APRENDIENDO DE PARTE DEL MAESTRO, YA QUE ESTE CAMPO DE LA TECNOLOGIA ME INTERESA DEMASIADO Y QUISIERA PODER DESTACARME COMO UN BUEN DESARROLLADOR

